# --------------------------------------------------
# Site settings
# --------------------------------------------------
  
# Color
color:
  default: "#33333D"
  link: "#FFBE5B"

# Favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Keywords
keywords: zhaoo, hexo-theme-zhaoo

# Preview
preview:
  enable: true
  model: wave  #cloud
  welcome_image: /images/theme/welcome-image.jpg
  motto:
    default: 你突然对我说，七里香的名字很美~
    api:  http://api.lovelive.tools/api/SweetNothings

# Menu
menu:
  home: / || 首页
  art : http://u-to-world.com:8080/index.html || 作品(我的音乐)
#  galleries: /galleries || 摄影
  archives: /archives || 归档
  tags: /tags || 标签
  categories: /categories || 分类
  about: /about || 关于

# Copyright
copyright: <p>Copyright© 2019-2020 | <a target="_blank" href="http://blog.u-to-world.com">小笼包</a> .AllRightsReserved</p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=694534942 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://www.instagram.com/izhaoo/ || iconinstagram || '#DA2E76'
  github: https://github.com/godlikedeveloper || icongithub-fill || '#24292E'
  email: mailto:694534942@qq.com || iconmail

# Fab (FloatActionButton)
fab:
  enable: true
  alwaysShow: false

# --------------------------------------------------
# Post settings
# --------------------------------------------------

# Post image
post_image: /images/theme/post-image.jpg

# Donate
donate:
  alipay: http://img.u-to-world.com/blog/alipay.png
  wechat: http://img.u-to-world.com/blog/weixinpay.png

# --------------------------------------------------
# Page settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 摄影
  subtitle: Photography

# --------------------------------------------------
# Comment settings
# --------------------------------------------------

comments:
  enable: true
  type: valine
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId: XgHS51JuLkeipj92BK4KyIEI-gzGzoHsz
  appKey: LHxBDnRt6RQCuByhRfp1pkVN
  placeholder: ヾﾉ≧∀≦)o来啊，快活啊!
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  appKey:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Lazyload
lazyload:
  enable: true
  onlyPost: false
  loadingImage: /images/theme/loading.gif

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs:

# FancyBox
fancybox: true

# Pjax
pjax: false

index_generator:
  path: ''
  per_page: 9
  order_by: -date
  
# HighLight
highlight:
  enable: true
  line_number: true
  auto_detect: true
  hljs: true
  tab_replace:

# --------------------------------------------------
# Script settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  justifiedGallery_js: https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.7.0/js/jquery.justifiedGallery.min.js
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/dracula.min.css
  iconfont_css: //at.alicdn.com/t/font_1445822_58xq2j9v1id.css
  justifiedGallery_css: https://cdn.bootcdn.net/ajax/libs/justifiedGallery/3.7.0/css/justifiedGallery.min.css

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: #id
  google: #id
  tencent: #id
  cnzz: #id

# Custom
custom:
  head:
  foot:
  css:
  js:
